### ISSUE TITLE
[改修] 画面右上のInstagramリンクをアイコンごと消す

### ISSUE THREAD

**Issue by hayatasatomi** [AtsukiTak/artell-portfolio#38]
## 該当箇所

- headerのインスタロゴ

## 改修内容

- headerのインスタロゴを消去する

## 改修理由

- 作家のポートフォリオページにARTELLのインスタがあるのが不自然
- ARTELLインスタのIDが変更され、リンク切れになっている

**Comment by AtsukiTak** [comment]
https://github.com/AtsukiTak/artell-portfolio/commit/4b2c71238c6c7df8411fa660361cb70a84315e51
