### ISSUE TITLE
作品登録後のアラート、2重表示される

### ISSUE THREAD

**Issue by hayatasatomi** [AtsukiTak/artell-portfolio#54]
作品登録時に
・新しい作品を追加しました！
・作品が登録されました！
の2つがそれぞれ alert でて、後者に関しては登録に失敗しても必ず出るようになってる

**Comment by AtsukiTak** [comment]
- 作品が登録されました！アラートを消す

**Comment by AtsukiTak** [comment]
fix with 7a8ff1f2a8314684813708083bf11f5e01cf5013
